from __future__ import annotations

from enum import StrEnum


class NodeType(StrEnum):
    LEGAL_ENTITY = "LEGAL_ENTITY"
    FUND_SERIES = "FUND_SERIES"
    SHARE_CLASS = "SHARE_CLASS"
    SECURITY = "SECURITY"
    PERSON = "PERSON"
    REPORTING_OWNER = "REPORTING_OWNER"


class EdgeType(StrEnum):
    SAME_AS = "SAME_AS"
    SERIES_OF_REGISTRANT = "SERIES_OF_REGISTRANT"
    CLASS_OF_SERIES = "CLASS_OF_SERIES"
    ISSUED_BY = "ISSUED_BY"
    REPORTED_HOLDING = "REPORTED_HOLDING"
    ACCOUNTING_PARENT = "ACCOUNTING_PARENT"
    ACCOUNTING_ULTIMATE_PARENT = "ACCOUNTING_ULTIMATE_PARENT"
    FUND_MANAGED_BY = "FUND_MANAGED_BY"
    SUBFUND_OF = "SUBFUND_OF"
    BRANCH_OF = "BRANCH_OF"
    GLEIF_RELATIONSHIP = "GLEIF_RELATIONSHIP"
    BANK_CONTROL_PARENT = "BANK_CONTROL_PARENT"
    BENEFICIAL_OWNER = "BENEFICIAL_OWNER"
    SIGNIFICANT_CONTROL = "SIGNIFICANT_CONTROL"
    INSIDER_OF = "INSIDER_OF"
    SUCCEEDED_BY = "SUCCEEDED_BY"
